name: Build Docker image

on:
  workflow_dispatch:
  push:
    branches:
      - main
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Generate lowercase repo name for docker registry
        id: reponame
        uses: ASzc/change-string-case-action@v5
        with:
          string: ${{ github.repository }}
      - name: tag and push devel image
        uses: docker/build-push-action@v3
        with:
          push: true
          file: Containerfile
          tags: ghcr.io/${{ steps.reponame.outputs.lowercase }}:latest
          labels: ${{ steps.meta.outputs.labels }}
      - name: tag and push release image
        if: github.event_name == 'release'
        uses: docker/build-push-action@v3
        with:
          push: true
          file: Containerfile
          # tags: ghcr.io/${{ steps.reponame.outputs.lowercase }}:${{ github.event.release.tag_name }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
